### ISSUE TITLE
Just wanted to say thanks

### ISSUE THREAD

**Issue by heumn** [rnystrom/SimpleWeather#5]
This made my learning curve for IGListKit much easier. So just wanted to say than you so much for sharing!

Side note, when I launched the app I didnt realize that you could scroll sideways the hourly forcasts before I read the code 🙈  if you made the size so that the last cell was cut off, it would maybe be easier to see? 🤔 

Regardless. You are frikkin awesome and good luck with the app. Looks sweeeet 💯

**Comment by heumn** [comment]
So not an issue, closed :)

**Comment by rnystrom** [comment]
@heumn thank you!! Love the hourly UI tip, going to do that 🙌

**Comment by poonamdhomane** [comment]
Hey , I also want to say thanks..really because of your sample i could  learn IGListKit easily.
I found this very late ,,still really happy  now :)
