### ISSUE TITLE
Adding shadow with corner radius

### ISSUE THREAD

**Issue by kanumuri9593** [rnystrom/SimpleWeather#6]
@rnystrom I started working with IGListKit and using your projects Simple weather and Freetime to achieve my designs and requirements,
with your Rounded cell class from simple weather I was able to achieve this 
![image uploaded from ios 8](https://user-images.githubusercontent.com/16531000/28972943-a95a7dd6-78ff-11e7-8564-7e7587a2e115.jpg)

But I was trying to to extend your class to acheive something like this 

![image uploaded from ios 7](https://user-images.githubusercontent.com/16531000/28972959-baecc3b0-78ff-11e7-8449-a14eb890c79a.jpg)
a shadow with corner radius as the new iOS 11 App store design
I have tried several solutions nothing achieved my design I Followed some examples to add a second layer behind the corner radius  but its not working 
can you hep me out 

Thank You

**Comment by rnystrom** [comment]
@kanumuri9593 you're going to need to use either a custom `UICollectionViewLayout` or decoration view to get this working. Here are some useful resources:

- [How to create a section background](http://strawberrycode.com/blog/how-to-create-a-section-background-in-a-uicollectionview-in-ios-swift/)
- [Collection view demos](https://github.com/SebastienMichoy/CollectionViewsDemo)
- [How to add a decoration view](https://markpospesel.wordpress.com/2012/12/11/decorationviews/)
- [Apple custom layout guide](https://developer.apple.com/library/content/documentation/WindowsViews/Conceptual/CollectionViewPGforIOS/CreatingCustomLayouts/CreatingCustomLayouts.html)

**Comment by rnystrom** [comment]
Also this probably belongs on IGListKit, not here

**Comment by kanumuri9593** [comment]
Thanks for your response I got better understanding now, will try as you suggested, and I opened an Issue as The Rounded Cell class is part of this Project but will open any such in IGListKit going forward
Thank you
