### ISSUE TITLE
the detail screen is only loading 

### ISSUE THREAD

**Issue by poonamdhomane** [rnystrom/SimpleWeather#7]
the detail screen is only loading, not showing any data

**Comment by rnystrom** [comment]
Did you create a weather underground API key and update `Secrets.swift`?

**Comment by poonamdhomane** [comment]
no. what is that ? what should be this weather API key

**Comment by rnystrom** [comment]
You need to make your own account and [API key here](https://www.wunderground.com/weather/api/) and then put it [here](https://github.com/rnystrom/SimpleWeather/blob/2931496577b88c291834c294d19f05c9a43d8887/SimpleWeather/Classes/Systems/API.swift#L11).
